# NOTE:
# there are security implications of allow_remote_control;
# any machine that we are connected to can run the commands
# specified in the remote_control_password section;
# it is critical that we only allow read commands here
# (e.g. send-text definitely CANNOT be used!)
allow_remote_control true
remote_control_password "" launch get-text get-colors

# basic formatting
font_size 14.0
cursor_shape block
shell_integration no-cursor
show_hyperlink_targets yes

# light background theme
background #ffffff
foreground #000000

# scrolling
scrollback_lines 10000
scrollback_indicator_opacity 1.0
wheel_scroll_multiplier 5.0
wheel_scroll_min_lines 1

# disable bell
enable_audio_bell no
visual_bell_duration 0
visual_bell_color #ffcccc

# add shift-only scroll bindings
map shift+up scroll_line_up
map shift+down scroll_line_down
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
